name: audio_video_progress_bar
description: A progress bar widget to show or change the position of an audio or
  video stream.
version: 2.0.2
homepage: https://github.com/suragch/audio_video_progress_bar
funding:
  - https://www.buymeacoffee.com/suragchdev
topics:
  - audio
  - video
  - progress-bar

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter: null

screenshots:
  - description: 'Examples of a working progress bar.'
    path: supplemental/progress_bar_demo.gif
  - description: 'Progress bar with a custom theme.'
    path: supplemental/custom_theme.png
  - description: 'Progress bar with a custom dark theme.'
    path: supplemental/dark_theme.png
  - description: 'Using a progress bar (play button not included).'
    path: supplemental/progress_bar_demo_with_buttons.gif
  - description: 'Progress bar with side labels.'
    path: supplemental/side_labels.png